### ISSUE TITLE
Issues with Locator Services

### ISSUE THREAD

**Issue by zees98** [adityajoshi12/Flutter-Stacked#10]
Greetings,
First of all, I must say thank you for the extension. Secondly, I just set up a project with your extension. But I keep getting various exceptions when using locator services. I was using some generation extension earlier but it had issues as well after Flutter 3.3 update. I have attached the issues below. TIA

**NavigationService**
Error: 
`════════ Exception caught by gesture ═══════════════════════════════════════════
You are trying to use contextless navigation without
      a GetMaterialApp or Get.key.
      If you are testing your app, you can use:
      [Get.testMode = true], or if you are running your app on
      a physical device or emulator, you must exchange your [MaterialApp]
      for a [GetMaterialApp].
════════════════════════════════════════════════════════════════════════════════`

**Snackbar Service**
`E/flutter (27379): #7      SnackbarService.showSnackbar
package:stacked_services/…/snackbar/snackbar_service.dart:68
E/flutter (27379): #8      AdminDashboardViewModel.goToReminders
package:rod_client_app/…/admin_dashboard/admin_dashboard_view_model.dart:20
E/flutter (27379): #9      _InkResponseState.handleTap
package:flutter/…/material/ink_well.dart:1072
E/flutter (27379): #10     GestureRecognizer.invokeCallback
package:flutter/…/gestures/recognizer.dart:253
E/flutter (27379): #11     TapGestureRecognizer.handleTapUp
package:flutter/…/gestures/tap.dart:627
E/flutter (27379): #12     BaseTapGestureRecognizer._checkUp
package:flutter/…/gestures/tap.dart:306
E/flutter (27379): #13     BaseTapGestureRecognizer.acceptGesture
package:flutter/…/gestures/tap.dart:276
E/flutter (27379): #14     GestureArenaManager.sweep
package:flutter/…/gestures/arena.dart:163
E/flutter (27379): #15     GestureBinding.handleEvent
package:flutter/…/gestures/binding.dart:464
E/flutter (27379): #16     GestureBinding.dispatchEvent
package:flutter/…/gestures/binding.dart:440
E/flutter (27379): #17     RendererBinding.dispatchEvent
package:flutter/…/rendering/binding.dart:337
E/flutter (27379): #18     GestureBinding._handlePointerEventImmediately
package:flutter/…/gestures/binding.dart:395
E/flutter (27379): #19     GestureBinding.handlePointerEvent
package:flutter/…/gestures/binding.dart:357
E/flutter (27379): #20     GestureBinding._flushPointerEventQueue
package:flutter/…/gestures/binding.dart:314
E/flutter (27379): #21     GestureBinding._handlePointerDataPacket
package:flutter/…/gestures/binding.dart:295
E/flutter (27379): #22     _invoke1 (dart:ui/hooks.dart:167:13)
E/flutter (27379): #23     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:341:7)
E/flutter (27379): #24     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)`

**Main.dart**
`void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  setupLocator();
  var app = await Firebase.initializeApp();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      theme: ThemeData(
        appBarTheme: AppBarTheme(
          backgroundColor: Colors.white,
          toolbarTextStyle: GoogleFonts.roboto(color: Colors.white),
        ),
      ),
      routeInformationParser: AppRouter().defaultRouteParser(),
      routerDelegate: AppRouter().delegate(),
      routeInformationProvider: AppRouter().routeInfoProvider(),
    );
  }
}`

Edit: Added main.dart code

**Comment by adityajoshi12** [comment]
Seems like you are using `get` package for routing, if that is the case then you need to `GetMaterialApp` instead of `MaterialApp.router` and update `MyApp ` class as per the  `GetMaterialApp`.
